version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/btleplug"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/btleplug/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_btleplug"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_btleplug/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/btleplug/native"
    schedule:
      interval: weekly
